engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - lib/**
exclude_paths:
- spec/**/*
